pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven'
        DOCKER_IMAGE = 'zli9a/e-banking'
        DOCKER_TAG = "v${BUILD_NUMBER}"
        DOCKER_CREDENTIALS = '262777'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/Anassaitouaguerd/E-banking.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                sh 'cd ebanking && ${MAVEN_HOME}/bin/mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'cd ebanking && ${MAVEN_HOME}/bin/mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh """
                        cd ebanking
                        docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
                        docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
                    """
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    // Login to Docker Hub and push the image
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh """
                            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                            docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
                            docker push ${DOCKER_IMAGE}:latest
                            docker logout
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! Docker image has been pushed to Docker Hub'
        }
        failure {
            echo 'Pipeline failed!'
        }
        always {
            // Clean up Docker images
            sh """
                docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG}
                docker rmi ${DOCKER_IMAGE}:latest
            """
        }
    }
}